sudo: false
dist: trusty
language: node_js
node_js: 6

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g bower
  - npm install gemini-sauce
  - bower install
before_script:
  - gulp lint
script:
  - gemini test test/visual